const Database = require('./db')
const createProffy = require('./create_proffy')

Database.then(async (db) => {
  // Insert data
  proffyValue = {
    name: "Diego Fernandes", 
    avatar: "https://avatars2.githubusercontent.com/u/2254731?s=400&u=0ba16a79456c2f250e7579cb388fa18c5c2d7d65&v=4", whatsapp: "8019870373", 
    bio: "Enthusiast of the best technologies in Chemistry.<br><br>Passionate about exploding things in the lab and for changing people's lives through experiences. More than 200.000 been through my experiments.", 
  }

  classValue = {
    subject: "Chemistry", 
    cost: "20", 
    // proffy_id will be generated by the database
  }

  classScheduleValues = [
    // class_id will be generated by the database after registering class
    {
      weekday: 1,
      time_from: 720,
      time_to: 1220
    },
    {
      weekday: 0,
      time_from: 520,
      time_to: 1220
    }
  ]

  // await createProffy(db, {proffyValue, classValue, classScheduleValues})

  // Query data
  
  // All proffys
  const selectedProffys = await db.all("SELECT * FROM proffys")
  // console.log(selectedProffys)

  // Consult available classes of a certain teacher
  // and bring all data from them
  const selectClassesAndProffys = await db.all(`
    SELECT classes.*, proffys.*
    FROM proffys
    JOIN classes ON (classes.proffy_id = proffys.id)
    WHERE classes.proffy_id = 1;
  `)
  // console.log(selectClassesAndProffys)

  // The chosen time, for instance, is from 8am to 6pm
  // time_from (8am) needs to be before or equal to time selected
  // time_to needs to be above

  const selectedClassesSchedules = await db.all(`
    SELECT class_schedule.*
    FROM class_schedule
    WHERE class_schedule.class_id = "1"
    AND class_schedule.weekday = "0"
    AND class_schedule.time_from <= "1300"
    AND class_schedule.time_to > "1300"
  `)
  
  // console.log(selectedClassesSchedules)

})